# Assignment


Array Creation

In [2]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 3.3 MB/s eta 0:00:00m eta 0:00:010:00:01


In [3]:
import numpy as np

In [14]:
arr1 = np.arange(10,51)
arr2 = np.arange(1,10).reshape(3,3)
arr3 = np.ones((5,5))
print(arr1)
print(arr2)
print(arr3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Array Operations

In [18]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)
arr1,arr2

(array([[0.08194703, 0.08328658, 0.30971993],
        [0.5928155 , 0.16336861, 0.16324557],
        [0.33301412, 0.92976454, 0.56263629]]),
 array([[0.42044953, 0.4721272 , 0.05438915],
        [0.61448053, 0.94271045, 0.11491265],
        [0.11723218, 0.16398281, 0.91525217]]))

In [19]:
arr1 + arr2

array([[0.50239655, 0.55541378, 0.36410908],
       [1.20729603, 1.10607906, 0.27815822],
       [0.4502463 , 1.09374735, 1.47788845]])

In [20]:
arr1 - arr2

array([[-0.3385025 , -0.38884062,  0.25533078],
       [-0.02166502, -0.77934184,  0.04833292],
       [ 0.21578193,  0.76578173, -0.35261588]])

In [21]:
arr1 * arr2

array([[0.03445459, 0.03932186, 0.0168454 ],
       [0.36427358, 0.15400929, 0.01875898],
       [0.03903997, 0.1524654 , 0.51495408]])

In [22]:
arr1 / arr2

array([[0.19490337, 0.17640709, 5.69451651],
       [0.96474254, 0.1732967 , 1.4206057 ],
       [2.84063736, 5.66989018, 0.61473363]])

Slicing and Indexing

In [33]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
arr[arr % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [36]:
arr[: : 3]

array([ 1,  4,  7, 10, 13, 16, 19])

Reshape and Flatten


In [37]:
arr = np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [45]:
arr = arr.reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
arr_2nd = arr[: , 1]
arr_2nd

array([ 2,  6, 10, 14])

In [47]:
arr = arr.flatten()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Statistical Operations

In [53]:
random_arr = np.random.randint(1,100,100)
random_arr

array([70, 90, 54, 37, 17, 38, 52, 26, 23, 76, 16, 59, 76, 50, 73, 98, 87,
       49, 33, 12, 56, 23, 84, 60, 30, 51, 60,  3, 74, 58, 79, 35, 60, 50,
        1, 30,  1, 98, 54, 56, 62, 71, 64, 31, 16, 63, 64, 85, 73, 31, 24,
       18, 37, 41, 76, 37, 31, 14, 96, 78, 80,  4, 78, 78, 76, 56, 99, 78,
       39,  4, 52,  1, 89, 49, 75, 45, 75, 80, 63, 76, 31, 95, 70, 22, 22,
       98,  6, 90, 30, 54, 17, 69, 78, 17, 34, 81, 87, 80,  9, 43])

In [61]:
print(np.mean(random_arr))

52.41


In [63]:
print(np.median(random_arr))

55.0


In [64]:
print(np.std(random_arr))

27.51548473132901


In [65]:
print(np.var(random_arr))

757.1019


In [66]:
print(np.argmax(random_arr))

66


In [67]:
print(np.argmin(random_arr))

34
